# GITHUB_WORKSPACE and SNOWFLAKE_ env vars must be set.  SnowCLI uses $SNOWFLAKE_PASSWORD
# https://github.com/mdigian/sfguide-data-engineering-with-notebooks/settings/secrets/actions
name: Deploy Demo Objects

on: 
  push:
    branches:
      - main 
      
  workflow_dispatch:

jobs:
  deploy:
    runs-on: ubuntu-latest

    steps:

      - name: Checkout repository  
        uses: actions/checkout@v4

      - name: Setup Python 3.10
        uses: actions/setup-python@v5
        with:
          python-version: '3.10'

      - name: Install Python packages
        run:  pip install -r requirements.txt

      - name: Deploy notebooks
        env:
          SF_ACCOUNT:   ${{ secrets.SNOWFLAKE_ACCOUNT   }}
          SF_USER:      ${{ secrets.SNOWFLAKE_USER      }}
          SF_PWD:       ${{ secrets.SNOWFLAKE_PASSWORD  }}
          SF_ROLE:      ${{ secrets.SNOWFLAKE_ROLE      }}
          SF_WH:        ${{ secrets.SNOWFLAKE_WAREHOUSE }}
          SF_DB:        ${{ secrets.SNOWFLAKE_DATABASE  }}
          SF_SCHEMA:    ${{ secrets.SNOWFLAKE_SCHEMA    }}
        run: |
          snow sql -q "ALTER GIT REPOSITORY DEMO_GIT_REPO FETCH"                                                                                 --temporary-connection --account $SF_ACCOUNT --user $SF_USER --role $SF_ROLE --warehouse $SF_WH --database $SF_DB --schema $SD_SCHEMA
          snow sql -q "EXECUTE IMMEDIATE FROM @DEMO_GIT_REPO/branches/main/scripts/deploy_notebooks.sql USING (env => 'PROD', branch => 'main')" --temporary-connection --account $SF_ACCOUNT --user $SF_USER --role $SF_ROLE --warehouse $SF_WH --database $SF_DB --schema $SF_SCHEMA

          : # Ideally Snow CLI and Python Connector are configured from env vars
          
          : # python $GITHUB_WORKSPACE/scripts/deploy_task_dag.py DEMO_DB PROD_SCHEMA
